version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: school-postgres
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - school-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: school-image:latest
    container_name: school-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/school
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - school-network

networks:
  school-network:
    driver: bridge